# Generated by Django 5.0 on 2023-12-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.server'),
        ),
    ]
