# Generated by Django 5.0 on 2023-12-26 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_member_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
