# Generated by Django 5.0 on 2023-12-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
    ]
