# Generated by Django 4.2.8 on 2023-12-27 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uniqueid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
